version: '3.8'

x-global: &default-platform
  platform: ${PLATFORM:-linux/arm64}

services:
  zookeeper:
    <<: *default-platform
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    <<: *default-platform
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  minio:
    <<: *default-platform
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  elasticsearch:
    <<: *default-platform
    image: arm64v8/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  spark:
    <<: *default-platform
    image: bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    depends_on:
      - kafka
      - minio
      - elasticsearch

  airflow:
    <<: *default-platform
    image: puckel/docker-airflow:1.10.9
    container_name: airflow
    restart: always
    depends_on:
      - kafka
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    ports:
      - "8081:8080"
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./zimbozapp/.env:/usr/local/airflow/.env

  bot:
    <<: *default-platform
    build: ./bot
    container_name: telegram-bot
    env_file:
      - ../.env
    depends_on:
      - elasticsearch
    restart: always

volumes:
  minio_data:
  esdata: 